# Generated by Django 4.1.3 on 2024-01-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_remove_user_login_type_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user_management.friendrequest'),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
