# Generated by Django 4.1.3 on 2024-01-11 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_friendrequest_friends_alter_friendrequest_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friends_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
